/**
 * Pure oxygen-simulation functions.  No ECS / DOM dependencies — fully unit-testable.
 *
 * O2 levels are represented as a percentage in the range [0, 100].
 */

// ── Rate constants ────────────────────────────────────────────────────────────

/** O2 per second regenerated by a powered OXYGEN system. */
export const O2_REGEN_RATE  = 8;

/** O2 per second lost when the OXYGEN system is unpowered. */
export const O2_DECAY_RATE  = 2;

/** Additional O2 per second lost when a hull breach is present. */
export const O2_BREACH_RATE = 20;

/**
 * Fraction of the O2 difference closed per second when equalizing two adjacent rooms.
 * Higher = faster equalization.
 */
export const ROOM_EQ_RATE  = 1.5;

/**
 * Fraction of the O2 difference closed per second when a room vents into space.
 * Much higher than ROOM_EQ_RATE so the room depressurises rapidly.
 */
export const SPACE_EQ_RATE = 2.0;

// ── Core functions ────────────────────────────────────────────────────────────

/**
 * Computes the new O2 level for a single room after one simulation step.
 *
 * - Powered OXYGEN system: O2 slowly regenerates at {@link O2_REGEN_RATE} per second.
 * - Unpowered:             O2 decays at {@link O2_DECAY_RATE} per second.
 * - Hull breach:           adds {@link O2_BREACH_RATE} per second on top of the base decay.
 *
 * Result is clamped to [0, 100].
 *
 * @param currentO2  Current O2 level (0–100).
 * @param isPowered  Whether the OXYGEN system has ≥ 1 power allocated.
 * @param hasBreach  Whether the room has a hull breach (separate from open doors).
 * @param dt         Elapsed seconds since the last frame.
 */
export function calculateO2Change(
  currentO2: number,
  isPowered: boolean,
  hasBreach: boolean,
  dt: number,
): number {
  let ratePerSec = isPowered ? O2_REGEN_RATE : -O2_DECAY_RATE;
  if (hasBreach) ratePerSec -= O2_BREACH_RATE;
  return Math.max(0, Math.min(100, currentO2 + ratePerSec * dt));
}

/**
 * Equalizes O2 levels between two adjacent rooms through an open door.
 *
 * Both rooms step toward their shared average at the given `rate` (fraction of the
 * difference closed per second).  If the door is closed, no equalization occurs.
 *
 * Pass `O2 = 0` for SPACE and use `rate = {@link SPACE_EQ_RATE}` to model rapid
 * depressurisation when an airlock is opened.
 *
 * @param roomAO2    O2 level of room A (0–100). Use 0 for SPACE.
 * @param roomBO2    O2 level of room B (0–100). Use 0 for SPACE.
 * @param doorIsOpen Whether the door between the rooms is currently open.
 * @param dt         Elapsed seconds since the last frame.
 * @param rate       Equalization rate (fraction of gap closed per second).
 *                   Defaults to {@link ROOM_EQ_RATE}.
 * @returns Tuple [newRoomAO2, newRoomBO2], both clamped to [0, 100].
 */
export function equalizeO2(
  roomAO2: number,
  roomBO2: number,
  doorIsOpen: boolean,
  dt: number,
  rate: number = ROOM_EQ_RATE,
): [number, number] {
  if (!doorIsOpen) return [roomAO2, roomBO2];

  const avg = (roomAO2 + roomBO2) / 2;
  const newA = Math.max(0, Math.min(100, roomAO2 + (avg - roomAO2) * rate * dt));
  const newB = Math.max(0, Math.min(100, roomBO2 + (avg - roomBO2) * rate * dt));
  return [newA, newB];
}
